### ISSUE TITLE
background noises

### ISSUE THREAD

**Issue by sarikakhot** [syl22-00/pocketsphinx.js#74] opened 2016-10-14 14:54 UTC
This library continuously interprets the background noises as well, which will kill my application flow since it is entirely voice command based.

Is there any way to set some configuration (ex. threshold) which can tell library to ignore noises and look for real voice?

**Comment by phihochzwei** [comment] 2016-11-07 14:39
Same problem for me. Anyone a solution for this ?

**Comment by jenweber** [comment] 2016-12-04 19:19
If you are using keyword detection and getting false positives with white noise, please see my comment in https://github.com/syl22-00/pocketsphinx.js/issues/60 .

If you are in continuous mode (transcribing sentences instead of listening for just one wake word), my solution does not apply.

**Comment by syl22-00** [comment] 2016-12-26 20:32
Duplicate of issue #60

**Closed by syl22-00** 2016-12-26 20:32 UTC
